### ISSUE TITLE
URLs for repos with a dash in the name are truncated at the dash

### ISSUE THREAD

**Issue by rshipp** [nishanthvijayan/GithubLatestProjects-Firefox#2]
For example, clicking to open `qw3rtman/git-fire` opens [qw3rtman/git](https://github.com/qw3rtman/git) instead. Same with `svg-mesh-3d` (`svg`), `safe-commit-hook` (`safe`), etc.

**Comment by nishanthvijayan** [comment]
Thanks for reporting the issue @rshipp :)

**Comment by rshipp** [comment]
If you don't mind my asking, why are you using that regex instead of just using repo.html_url directly?

**Comment by nishanthvijayan** [comment]
Firefox has a very strict add-on review policy.I was asked by a reviewer to make sure to verify that the repo.html_url is a url before inserting it into the DOM,to prevent remote script execution.
See:
https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions/XUL_School/DOM_Building_and_HTML_Insertion

![screenshot from 2015-10-09 14 02 34](https://cloud.githubusercontent.com/assets/7537349/10389406/c730223e-6e8e-11e5-92b6-3e65547946ba.png)

**Comment by rshipp** [comment]
Ah, that makes sense. Thanks!
